## Import Library

In [2]:
#202331021_Pramesti Anggreini Romadona
import cv2
import numpy as np

## Membaca Citra

In [5]:
#202331021_Pramesti Anggreini Romadona
citra = cv2.imread('bird.jpg')

In [30]:
#202331021_Pramesti Anggreini Romadona
cv2.imshow("Citra asli", citra)
cv2.waitKey()
cv2.destroyAllWindows()

## Dimensi Citra

In [9]:
#202331021_Pramesti Anggreini Romadona
print(citra.shape)
print(citra.dtype)

(1024, 1024, 3)
uint8


## splitting Citra RGB/BGR

In [32]:
#202331021_Pramesti Anggreini Romadona
b = citra[:,:,0]
g = citra[:,:,1]
r = citra[:,:,2]

## RGB to Grayscale

In [57]:
#202331021_Pramesti Anggreini Romadona
panjang = len(citra) #menghitung baris
lebar = len(citra[0]) #menghitung kolom 

citra_gray = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        citra_gray[i,j] = 0.2989 * r[i,j] + 0.587 * g[i,j] + 0.1141 * b[i,j] #merah= 29,89% ; hijau = 58,7% ; biru = 11,41%

citra_gray = citra_gray.astype(np.uint8)

cv2.imshow("citra grayscale", citra_gray)
cv2.waitKey()
cv2.destroyAllWindows()

In [35]:
#202331021_Pramesti Anggreini Romadona
print(citra)

[[[ 29  35  16]
  [ 33  42  22]
  [ 36  47  31]
  ...
  [ 79 224 245]
  [ 76 222 244]
  [ 75 221 243]]

 [[ 22  28   9]
  [ 23  32  12]
  [ 23  34  18]
  ...
  [ 75 220 241]
  [ 73 219 241]
  [ 71 217 239]]

 [[ 23  27   8]
  [ 20  26   7]
  [ 15  26  10]
  ...
  [ 74 221 241]
  [ 72 218 240]
  [ 71 217 239]]

 ...

 [[ 18  30  10]
  [  6  18   0]
  [  4  16   0]
  ...
  [ 11  22   6]
  [  8  19   3]
  [  9  20   4]]

 [[ 24  40  17]
  [ 13  29   6]
  [ 14  26   6]
  ...
  [ 31  44  28]
  [ 26  39  23]
  [ 26  40  22]]

 [[ 42  58  35]
  [ 54  70  47]
  [ 44  56  36]
  ...
  [ 36  52  35]
  [ 30  46  28]
  [ 27  43  25]]]


## Grayscale to Binary

In [61]:
#202331021_Pramesti Anggreini Romadona
panjang = len(citra) #menghitung baris
lebar = len(citra[0]) #menghitung kolom

ambang = 20

citra_biner = np.zeros((panjang,lebar))

for i in range (panjang):
    for j in range (lebar):
        if citra_gray[i,j] >= ambang:
            citra_biner[i,j] = 1
        else :
            citra_biner[i,j] = 0

cv2.imshow("citra binary", citra_biner)
cv2.waitKey()
cv2.destroyAllWindows()

In [38]:
#202331021_Pramesti Anggreini Romadona
print(citra_gray)

[[ 28  34  40 ... 213 211 210]
 [ 21  24  27 ... 209 208 206]
 [ 20  19  19 ... 210 207 206]
 ...
 [ 22  11   9 ...  15  12  13]
 [ 31  20  18 ...  37  32  33]
 [ 49  61  48 ...  45  38  35]]


In [39]:
#202331021_Pramesti Anggreini Romadona
print(citra_biner)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 0. 0. ... 1. 1. 1.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [49]:
#202331021_Pramesti Anggreini Romadona
print(citra_biner[50,50])

1.0
